let coffeeJson = [
    {id:1, name:'Café Expresso', img:'images/cafeExpresso.jpg', price:8.00, description:'Enquanto “expresso” significa algo rápido, de feitura dinâmica, o termo “espresso” tem sua origem italiana, e vem de “espremido”. No dicionário em português, o correto é expresso, mas a palavra vem do italiano.'},
    {id:2, name:'Café Coado', img:'images/Coado.webp', price:10.00, description:'O café coado está no lar dos brasileiros há décadas, com diferentes nuances e modos de preparo, de acordo com a região.'},
    {id:3, name:'Café Americano', img:'images/Americano.webp', price:12.50, description:'O resultado é uma bebida suave, clarinha, que os americanos estão mais acostumados a tomar, como vemos em filmes.'},
    {id:4, name:'Latte Macchiato', img:'images/lattemachi.webp', price:15.00, description:'Esse é um dos tipos de cafés mais gostosos, na minha humilde opinião. E com certeza, uma das bebidas com café mais tradicionais e procuradas.'},
    {id:5, name:'Ristretto', img:'images/ricchi.webp', price:12.50, description:'O resultado vai ser uma dose forte, potente e altamente amarga.'},
    {id:6, name:'Café Latte', img:'images/cafeLatte.jpg', price:18.00, description:'O Café Latte não é apenas um café com leite, e nem um Macchiato. Ele é uma versão mais incorporada da bebida do grão às partes em leite e em espuma.'},
    {id:7, name:'Cappuccino', img:'images/capuchi.jpg', price:14.50, description:'O Cappuccino caseiro merece ser experimentado, até porque ele é versátil e pode ser feito de várias formas.'},
    {id:8, name:'Café Mocha', img:'images/Mocha.webp', price:14.50, description:'Para servir o Café Mocha, você despejará em uma xícara o café expresso quente, o leite vaporizado por cima e, em seguida, a calda, de forma a desenhar na espuma com essa finalização. O resultado é uma bebida doce e amarga, quase cremosa e simplesmente deliciosa.'}
];